coverage:
  status:
    project:
      default:
        # basic
        target: auto
        threshold: 0%
        base: auto
        if_ci_failed: error #success, failure, error, ignore
        informational: false
        only_pulls: false
