name: Tonkotsu CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v2
      with:
        node-version: 14.x
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    - run: npm run report-coverage
    - name: Codecov
      uses: codecov/codecov-action@v1.5.0
